module.exports = {
  apps: [
    {
      name: 'icarus-agent',
      script: 'agent.js',
      cwd: '/Users/nicholastsakonas/openclaw',
      watch: false,
      max_memory_restart: '500M',
      env_file: '.env',
      log_file: './logs/agent.log',
      error_file: './logs/agent-error.log',
      time: true,
      autorestart: false,  // CLI REPL — no TTY under PM2, exits immediately. Run manually: node agent.js
    },
    {
      name: 'icarus-server',
      script: 'server.js',
      cwd: '/Users/nicholastsakonas/openclaw',
      watch: false,
      max_memory_restart: '500M',
      env_file: '.env',
      log_file: './logs/server.log',
      error_file: './logs/server-error.log',
      time: true,
      autorestart: true,
    },
    {
      name: 'icarus-scheduler',
      script: 'scheduler.js',
      cwd: '/Users/nicholastsakonas/openclaw',
      watch: false,
      max_memory_restart: '500M',
      env_file: '.env',
      log_file: './logs/scheduler.log',
      error_file: './logs/scheduler-error.log',
      time: true,
      autorestart: true,
    },
    {
      name: 'icarus-dashboard',
      script: 'dashboard.js',
      cwd: '/Users/nicholastsakonas/openclaw',
      watch: false,
      max_memory_restart: '500M',
      env_file: '.env',
      log_file: './logs/dashboard.log',
      error_file: './logs/dashboard-error.log',
      time: true,
      autorestart: true,
    },
  ],
};
